version: "3"
services:
  app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=connectDB
    security_opt:
      - seccomp:unconfined
  app:
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - app-db